name: CI
on:
  pull_request:
    branches:
      - master

env:
  BASENAME: "polaris"
  SPACEMAN_DMM_VERSION: suite-1.7

jobs:
  file_tests:
    name: Run Linters
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Ensure +x on CI directory
        run: |
          chmod -R +x ./tools/ci
      - name: Install Tools
        run: |
          bash tools/ci/install_build_deps.sh
      - name: Run Tests
        run: |
          tools/ci/validate_files.sh
          tools/ci/build_tgui.sh

  DreamChecker:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
      - name: Setup Cache
        uses: actions/cache@26968a09c0ea4f3e233fdddbafd1166051a095f6
        with:
          path: $HOME/spaceman_dmm/$SPACEMAN_DMM_VERSION
          key: ${{ runner.os }}-spacemandmm-${{ env.SPACEMAN_DMM_VERSION }}
      - name: Install Dreamchecker
        run:  tools/ci/install-spaceman-dmm.sh dreamchecker
      - name: Run Dreamchecker
        run: ~/dreamchecker > ${GITHUB_WORKSPACE}/output-annotations.txt 2>&1
      - name: Annotate Lints
        uses: yogstation13/DreamAnnotate@34029606cd7c22a08a589e084f860c1cc287363c
        if: hashFiles('output-annotations.txt') != ''
        with:
          outputFile: output-annotations.txt

  unit_tests:
    name: Integration Tests
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Ensure +x on CI directory
        run: |
          chmod -R +x ./tools/ci
      - name: Setup Cache
        uses: actions/cache@v2
        with:
          path: $HOME/BYOND
          key: ${{ runner.os }}-byond
      - name: Install RUST_G Dependencies
        run: |
          sudo dpkg --add-architecture i386
          sudo apt update || true
          sudo apt install libc6:i386 libgcc1:i386 libstdc++6:i386 libssl1.1:i386 zlib1g:i386
      - name: Unit Tests
        run: |
          tools/ci/install_byond.sh
          tools/ci/compile_and_run.sh
        env:
          TEST_DEFINE: "UNIT_TEST"
          TEST_FILE: "code/_unit_tests.dm"
          RUN: "1"
      - name: Compile POIs (no run)
        run: |
          tools/ci/install_byond.sh
          tools/ci/compile_and_run.sh
        env:
          TEST_DEFINE: "MAP_TEST"
          TEST_FILE: "code/_map_tests.dm"
          RUN: "0"
      - name: Compile away missions (no run)
        run: |
          tools/ci/install_byond.sh
          tools/ci/compile_and_run.sh
        env:
          TEST_DEFINE: "AWAY_MISSION_TEST"
          TEST_FILE: "code/_away_mission_tests.dm"
          RUN: "0"
